#!/bin/sh
# OpenChimera config generator
# Reads UCI configuration and generates a Chimera (clash-rs) compatible config.yaml
#
# Compatible with Chimera / clash-rs — NOT Mihomo / Nikki
# Unsupported Nikki-only fields (auto-redirect, auto-detect-interface,
# disable-icmp-forwarding) are intentionally excluded.
#
# Usage (standalone):
#   openchimera-config-gen
#   WORK_DIR=/tmp/myrun openchimera-config-gen
#
# Called from init script: /etc/init.d/openchimera start
#   → loads UCI, generates $WORK_DIR/config.yaml, validates with mihomo -t

set -e

PROG="${PROG:-/usr/bin/mihomo}"
WORK_DIR="${WORK_DIR:-/etc/openchimera/run}"
CONFIG_FILE="${CONFIG_FILE:-config.yaml}"

# ---------------------------------------------------------------------------
# Helper: log to syslog
# ---------------------------------------------------------------------------
log_msg() {
	logger -t "openchimera-config-gen" "$@"
}

# ---------------------------------------------------------------------------
# Helper: emit a YAML key: scalar line (skips if value is empty)
# ---------------------------------------------------------------------------
yaml_kv() {
	_key="$1"
	_val="$2"
	[ -n "$_val" ] && echo "${_key}: ${_val}"
}

# ---------------------------------------------------------------------------
# Ensure runtime directory exists
# ---------------------------------------------------------------------------
mkdir -p "$WORK_DIR" || {
	log_msg "FATAL: cannot create runtime directory '${WORK_DIR}'"
	exit 1
}

# ---------------------------------------------------------------------------
# Source OpenWrt UCI library (idempotent)
# ---------------------------------------------------------------------------
. /lib/functions.sh 2>/dev/null || {
	log_msg "FATAL: cannot source /lib/functions.sh (not OpenWrt?)"
	exit 1
}

# ---------------------------------------------------------------------------
# Load UCI configuration
# ---------------------------------------------------------------------------
config_load openchimera || {
	log_msg "FATAL: cannot load UCI config 'openchimera'"
	exit 1
}

# ---------------------------------------------------------------------------
# Read UCI values (with sensible defaults)
# ---------------------------------------------------------------------------

# --- Ports ---
config_get mixed_port  mixin mixed_port  7890
config_get socks_port  mixin socks_port  ''
config_get port        mixin port        ''

# --- API / External controller ---
config_get api_listen  mixin api_listen  '0.0.0.0:9090'
config_get secret      mixin secret      ''

# --- Logging ---
config_get log_level   config log_level  'info'

# --- TUN ---
config_get_bool tun_enabled    mixin tun_enabled    0
config_get       tun_device    mixin tun_device     'nikki'
config_get_bool tun_dns_hijack mixin tun_dns_hijack 0

# --- Routing ---
config_get tun_route_table routing tun_route_table 81

# ---------------------------------------------------------------------------
# Generate config.yaml — build the output file
# ---------------------------------------------------------------------------
generate_config() {
	echo "# Generated by OpenChimera config_gen.sh"
	echo "# Source: UCI package 'openchimera'"
	echo "# DO NOT EDIT -- changes are overwritten on service start / reload."
	echo "#"
	echo "# Chimera/clash-rs runtime configuration."
	echo "# Nikki/Mihomo-only fields (auto-redirect, auto-detect-interface,"
	echo "# disable-icmp-forwarding) are intentionally excluded -- they are"
	echo "# not supported by the Chimera core."
	echo ""

	# --- Ports ---
	yaml_kv "mixed-port" "${mixed_port:-7890}"

	# Optional ports: only emit if non-empty and non-zero
	if [ -n "$socks_port" ] && [ "$socks_port" != "0" ]; then
		yaml_kv "socks-port" "$socks_port"
	fi
	if [ -n "$port" ] && [ "$port" != "0" ]; then
		yaml_kv "port" "$port"
	fi

	echo ""

	# --- API / external controller ---
	yaml_kv "external-controller" "${api_listen:-0.0.0.0:9090}"
	if [ -n "$secret" ]; then
		yaml_kv "secret" "$secret"
	fi

	echo ""

	# --- Logging ---
	yaml_kv "log-level" "${log_level:-info}"

	# --- TUN block (only if enabled) ---
	if [ "${tun_enabled}" = "1" ]; then
		echo ""
		echo "tun:"
		echo "  enable: true"
		yaml_kv "  device"      "${tun_device:-nikki}"
		yaml_kv "  route-table" "${tun_route_table:-81}"

		if [ "${tun_dns_hijack}" = "1" ]; then
			echo "  dns-hijack:"
			echo '    - "0.0.0.0/0"'
			echo '    - "::/0"'
		fi
	fi
}

# Write the generated config to file
generate_config > "$WORK_DIR/${CONFIG_FILE}"

# ---------------------------------------------------------------------------
# Validate the generated config with the core binary
# ---------------------------------------------------------------------------
log_msg "Validating generated config with '${PROG} -t'..."
if "$PROG" -t -d "$WORK_DIR" -c "$CONFIG_FILE" >/dev/null 2>&1; then
	log_msg "Config validation PASSED"
	exit 0
else
	log_msg "Config validation FAILED — see below:"
	"$PROG" -t -d "$WORK_DIR" -c "$CONFIG_FILE" 2>&1 | while IFS= read -r line; do
		log_msg "  ${line}"
	done
	exit 1
fi
